Add access.conf template
ThePrudents/fwknopd pull request #2
Opened 2016-11-30 19:24 UTC by salandur

Add access.conf template
Render the template

2016-12-07 16:22 UTC, vovinacci requested changes
Almost there :)

2016-12-07 16:22 UTC, vovinacci commented on .travis.yml
> +
Remove blank line here

2016-12-07 16:22 UTC, vovinacci commented on README.md
> +
Remove blank line here

2016-12-07 16:22 UTC, vovinacci commented on tests/travis_test.yml
> +        hmac_base64: "hmac"
Do we use those vars?

2016-12-07 16:47 UTC, salandur commented on tests/travis_test.yml
> +        hmac_base64: "hmac"
Yes, we use those vars in the access.conf

2016-12-08 14:13 UTC, vovinacci approved these changes

2016-12-08 14:14 UTC, merged